apiVersion: apps/v1
kind: Deployment
metadata:
  name: dida-mlops-deployment
  namespace: dida-mlops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dida-mlops-application
  template:
    metadata:
      labels:
        app: dida-mlops-application
    spec:
      containers:
      - name: ml-devops-dida-task
        image: ghcr.io/jahednaghipoor/ml-devops-dida-task:main-final # image and its version
        command:
          - sh
          - -c
          - python src/ml_devops_dida_task/main.py
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "4Gi"