apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-api-ingress
  namespace: dida-mlops-test
spec:
  rules:
  - host: fast-api-dida.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fast-api-service
            port:
              number: 80
