apiVersion: v1
kind: Service
metadata:
  name: dida-mlops-service
  namespace: dida-mlops
spec:
  selector:
    app: dida-mlops-application # detect original and canary models and distribute request based on number of replicasets in each deployment (75% -25%)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
