apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
  namespace: dida-mlops-test
spec:
  selector:
    app: fast-api-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
