# This GitHub workflow sets up CI/CD workflows.
name: Deploy CICD for Project Workflow

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project Name'
        required: true
        default: ml_devops_dida_task

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Commit Changes
        id: commit
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout -b add-cicd-for-${{ github.event.inputs.project_name }}
          git add .github 
          git commit -m "Add CICD for ${{ github.event.inputs.project_name }}"
          git push origin add-cicd-for-${{ github.event.inputs.project_name }}
      - name: Create Pull Request
        id: pr
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base main --head add-cicd-for-${{ github.event.inputs.project_name }} --title "Deploy CICD for ${{ github.event.inputs.project_name }}" --body "This PR was generated by the Deploy CICD workflow."
