name: Setup Local Environment

on:
  workflow_dispatch:  # Allow manual trigger of the workflow
  push:
    branches:
      - main
      - master

jobs:
  setup_environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Docker Desktop and k3d
        if: runner.os == 'Windows' || runner.os == 'Mac'
        run: |
          # Install Docker Desktop on Windows or Mac
          # Please replace the download link with the latest version
          curl -fsSL https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe -o docker-desktop-installer.exe
          Start-Process -FilePath .\docker-desktop-installer.exe -ArgumentList '/quiet', '/norestart' -Wait
          # Install k3d
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
